GameGenreNeuronNetwork/Models/TrainingSet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameGenreNeuronNetwork.Models
{
    public class TrainingSet
    {
        public int Id { get; set; }
        public int GameGenreId { get; set; }
        public int GameAspectGroupId { get; set; }

        public GameGenre GameGenre { get; set; }
        
    }
}

GameGenreNeuronNetwork/Controllers/TrainingSetsController.cs
using GameGenreNeuronNetwork.Context;
using GameGenreNeuronNetwork.Models;
using GameGenreNeuronNetwork.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameGenreNeuronNetwork.Controllers
{
    public class TrainingSetsController : Controller
    {
        private readonly DatabaseContext _context;

        public TrainingSetsController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //optimize using joins
            var trainingSets = _context.TrainingSets.ToList();
            List<TrainingSetExtended> trainingSetExtended = new List<TrainingSetExtended>();
            foreach(var item in trainingSets)
            {
                var gameGenreName = _context
                    .GameGenres
                    .First(g => g.Id == item.GameGenreId)
                    .Name;

                var gameAspects = (from gr in _context.GameAspectGroups
                                    join asp in _context.GameAspects on gr.GameAspectId equals asp.Id
                                    where gr.GroupId == item.GameAspectGroupId
                                    select new GameAspectWithValue
                                    {
                                        Name = asp.Name,
                                        Value = gr.Value
                                    }).ToList();

                trainingSetExtended.Add(new TrainingSetExtended { Name = gameGenreName, GameAspects = gameAspects });
            }

            return View(trainingSetExtended);
        }

        public IActionResult Create()
        {
            var genres = _context.GameGenres.ToArray();
            var aspects = _context.GameAspects.Select(a => new GameAspectWithValue { Id = a.Id, Name = a.Name, Value = 0 }).ToArray();

            var model = new TrainingSetCreateViewModel { Genres = genres, Aspects = aspects };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TrainingSetCreateViewModel model)
        {
            int groupId;
            try
            {
                groupId = _context.GameAspectGroups.OrderBy(a=>a.GroupId).Last().GroupId + 1;
            }
            catch
            {
                groupId = 1;
            }
            var aspects = _context.GameAspects.ToList();
            foreach (var i in aspects)
            {
                _context.GameAspectGroups.Add(new GameAspectGroup { GroupId = groupId, GameAspectId = i.Id, Value = model.SelectedIds != null && model.SelectedIds.Count() > 0 && model.SelectedIds.Contains(i.Id) ? 1 : 0 });
            }
            _context.Add(new TrainingSet { GameGenreId = model.SelectedGenreId, GameAspectGroupId = groupId });
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

GameGenreNeuronNetwork/Views/TrainingSets/Create.cshtml
@model GameGenreNeuronNetwork.Models.ViewModels.TrainingSetCreateViewModel

@{
    ViewData["Title"] = "Create";
}



<h1>Create</h1>

    <h4>Training set</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            @using (Html.BeginForm("Create", "TrainingSets", FormMethod.Post))
            {
                <div class="form-group">
                    <label asp-for="Genres" class="control-label"></label>
                    @Html.DropDownList("SelectedGenreId", new SelectList(Model.Genres, "Id", "Name"), new { @class = "form-control" })
                </div>
                <ul>
                    @foreach (var aspect in Model.Aspects)
                    {
                        <li>
                            <input id="aspect@(aspect.Id)"
                                   type="checkbox"
                                   name="SelectedIds"
                                   value="@aspect.Id"
                                   @(aspect.Value == 1 ? "checked" : "") />
                            <label for="operator@(aspect.Id)">@aspect.Name</label>
                        </li>

                    }
                </ul>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            }
            </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

GameGenreNeuronNetwork/Views/TrainingSets/Index.cshtml
@model List<GameGenreNeuronNetwork.Models.ViewModels.TrainingSetExtended>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>
            @if (Model.Count>0)
            {
                @foreach (var aspect in Model[0].GameAspects)
                {
                    <th>
                        @aspect.Name
                    </th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                @foreach(var aspect in item.GameAspects)
                {
                    <td>
                        <p>@aspect.Value</p>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>